### ISSUE TITLE
Missing /model/ops Folder

### ISSUE THREAD

**Issue by pw-02** [tmlabonte/weakly-supervised-DETR#3]
Hello, I noticed that folder /model/ops is missing when I tried to deploy/build/run the solution. Can you please confirm if this is intentional or not? 
I was able to get it running by taking copy of /model/ops from [https://github.com/SHI-Labs/OneFormer/tree/main/oneformer/modeling/pixel_decoder/ops](url) but I had to swap around the names of some variables to get it to work, which suggests the code I copied across is different from what's expected.  Thanks for your help!

**Comment by tmlabonte** [comment]
Thanks for the catch! I've just added the correct folder.
